//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace SiemensHR.Classes {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet1 : DataSet {
        
        private AngajatiDataTable tableAngajati;
        
        public DataSet1() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet1(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Angajati"] != null)) {
                    this.Tables.Add(new AngajatiDataTable(ds.Tables["Angajati"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public AngajatiDataTable Angajati {
            get {
                return this.tableAngajati;
            }
        }
        
        public override DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Angajati"] != null)) {
                this.Tables.Add(new AngajatiDataTable(ds.Tables["Angajati"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableAngajati = ((AngajatiDataTable)(this.Tables["Angajati"]));
            if ((this.tableAngajati != null)) {
                this.tableAngajati.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet1.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableAngajati = new AngajatiDataTable();
            this.Tables.Add(this.tableAngajati);
        }
        
        private bool ShouldSerializeAngajati() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void AngajatiRowChangeEventHandler(object sender, AngajatiRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class AngajatiDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnAngajatID;
            
            private DataColumn columnAngajatorID;
            
            private DataColumn columnMarca;
            
            private DataColumn columnNumeIntreg;
            
            private DataColumn columnNume;
            
            private DataColumn columnPrenume;
            
            private DataColumn columnNumeAnterior;
            
            private DataColumn columnTitluID;
            
            private DataColumn columnPoza;
            
            private DataColumn columnPrenumeMama;
            
            private DataColumn columnPrenumeTata;
            
            private DataColumn columnStudiuID;
            
            private DataColumn columnAnAbsolvire;
            
            private DataColumn columnNrDiploma;
            
            private DataColumn columnDescriere;
            
            private DataColumn columnModIncadrare;
            
            private DataColumn columnProgramLucru;
            
            private DataColumn columnTelefon;
            
            private DataColumn columnDataNasterii;
            
            private DataColumn columnTaraNastereID;
            
            private DataColumn columnJudetNastereID;
            
            private DataColumn columnLocalitateNastere;
            
            private DataColumn columnStareCivila;
            
            private DataColumn columnNrCopii;
            
            private DataColumn columnSex;
            
            private DataColumn columnNationalitate;
            
            private DataColumn columnCNP;
            
            private DataColumn columnCNPAnterior;
            
            private DataColumn columnTipFisaFiscala;
            
            private DataColumn columnAniVechimeMunca;
            
            private DataColumn columnLuniVechimeMunca;
            
            private DataColumn columnZileVechimeMunca;
            
            private DataColumn columnAreCardBancar;
            
            private DataColumn columnSefID;
            
            private DataColumn columnActiv;
            
            private DataColumn columnSalariuBazaActual;
            
            private DataColumn columnIndemnizatieConducereActual;
            
            private DataColumn columnPerioadaDeterminata;
            
            private DataColumn columnDataPanaLa;
            
            private DataColumn columnNrContractMunca;
            
            private DataColumn columnDataInregContractMunca;
            
            private DataColumn columnInvaliditate;
            
            private DataColumn columnCategorieID;
            
            private DataColumn columnEmail;
            
            private DataColumn columnTelMunca;
            
            private DataColumn columnDeleted;
            
            private DataColumn columnPensionar;
            
            private DataColumn columnAreAlteVenituri;
            
            private DataColumn columnSolicitaDeduceri;
            
            private DataColumn columnPermMuncaEliberat;
            
            private DataColumn columnPermMuncaExpira;
            
            private DataColumn columnPermSedereEliberat;
            
            private DataColumn columnPermSedereExpira;
            
            private DataColumn columnNrPermisMunca;
            
            internal AngajatiDataTable() : 
                    base("Angajati") {
                this.InitClass();
            }
            
            internal AngajatiDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn AngajatIDColumn {
                get {
                    return this.columnAngajatID;
                }
            }
            
            internal DataColumn AngajatorIDColumn {
                get {
                    return this.columnAngajatorID;
                }
            }
            
            internal DataColumn MarcaColumn {
                get {
                    return this.columnMarca;
                }
            }
            
            internal DataColumn NumeIntregColumn {
                get {
                    return this.columnNumeIntreg;
                }
            }
            
            internal DataColumn NumeColumn {
                get {
                    return this.columnNume;
                }
            }
            
            internal DataColumn PrenumeColumn {
                get {
                    return this.columnPrenume;
                }
            }
            
            internal DataColumn NumeAnteriorColumn {
                get {
                    return this.columnNumeAnterior;
                }
            }
            
            internal DataColumn TitluIDColumn {
                get {
                    return this.columnTitluID;
                }
            }
            
            internal DataColumn PozaColumn {
                get {
                    return this.columnPoza;
                }
            }
            
            internal DataColumn PrenumeMamaColumn {
                get {
                    return this.columnPrenumeMama;
                }
            }
            
            internal DataColumn PrenumeTataColumn {
                get {
                    return this.columnPrenumeTata;
                }
            }
            
            internal DataColumn StudiuIDColumn {
                get {
                    return this.columnStudiuID;
                }
            }
            
            internal DataColumn AnAbsolvireColumn {
                get {
                    return this.columnAnAbsolvire;
                }
            }
            
            internal DataColumn NrDiplomaColumn {
                get {
                    return this.columnNrDiploma;
                }
            }
            
            internal DataColumn DescriereColumn {
                get {
                    return this.columnDescriere;
                }
            }
            
            internal DataColumn ModIncadrareColumn {
                get {
                    return this.columnModIncadrare;
                }
            }
            
            internal DataColumn ProgramLucruColumn {
                get {
                    return this.columnProgramLucru;
                }
            }
            
            internal DataColumn TelefonColumn {
                get {
                    return this.columnTelefon;
                }
            }
            
            internal DataColumn DataNasteriiColumn {
                get {
                    return this.columnDataNasterii;
                }
            }
            
            internal DataColumn TaraNastereIDColumn {
                get {
                    return this.columnTaraNastereID;
                }
            }
            
            internal DataColumn JudetNastereIDColumn {
                get {
                    return this.columnJudetNastereID;
                }
            }
            
            internal DataColumn LocalitateNastereColumn {
                get {
                    return this.columnLocalitateNastere;
                }
            }
            
            internal DataColumn StareCivilaColumn {
                get {
                    return this.columnStareCivila;
                }
            }
            
            internal DataColumn NrCopiiColumn {
                get {
                    return this.columnNrCopii;
                }
            }
            
            internal DataColumn SexColumn {
                get {
                    return this.columnSex;
                }
            }
            
            internal DataColumn NationalitateColumn {
                get {
                    return this.columnNationalitate;
                }
            }
            
            internal DataColumn CNPColumn {
                get {
                    return this.columnCNP;
                }
            }
            
            internal DataColumn CNPAnteriorColumn {
                get {
                    return this.columnCNPAnterior;
                }
            }
            
            internal DataColumn TipFisaFiscalaColumn {
                get {
                    return this.columnTipFisaFiscala;
                }
            }
            
            internal DataColumn AniVechimeMuncaColumn {
                get {
                    return this.columnAniVechimeMunca;
                }
            }
            
            internal DataColumn LuniVechimeMuncaColumn {
                get {
                    return this.columnLuniVechimeMunca;
                }
            }
            
            internal DataColumn ZileVechimeMuncaColumn {
                get {
                    return this.columnZileVechimeMunca;
                }
            }
            
            internal DataColumn AreCardBancarColumn {
                get {
                    return this.columnAreCardBancar;
                }
            }
            
            internal DataColumn SefIDColumn {
                get {
                    return this.columnSefID;
                }
            }
            
            internal DataColumn ActivColumn {
                get {
                    return this.columnActiv;
                }
            }
            
            internal DataColumn SalariuBazaActualColumn {
                get {
                    return this.columnSalariuBazaActual;
                }
            }
            
            internal DataColumn IndemnizatieConducereActualColumn {
                get {
                    return this.columnIndemnizatieConducereActual;
                }
            }
            
            internal DataColumn PerioadaDeterminataColumn {
                get {
                    return this.columnPerioadaDeterminata;
                }
            }
            
            internal DataColumn DataPanaLaColumn {
                get {
                    return this.columnDataPanaLa;
                }
            }
            
            internal DataColumn NrContractMuncaColumn {
                get {
                    return this.columnNrContractMunca;
                }
            }
            
            internal DataColumn DataInregContractMuncaColumn {
                get {
                    return this.columnDataInregContractMunca;
                }
            }
            
            internal DataColumn InvaliditateColumn {
                get {
                    return this.columnInvaliditate;
                }
            }
            
            internal DataColumn CategorieIDColumn {
                get {
                    return this.columnCategorieID;
                }
            }
            
            internal DataColumn EmailColumn {
                get {
                    return this.columnEmail;
                }
            }
            
            internal DataColumn TelMuncaColumn {
                get {
                    return this.columnTelMunca;
                }
            }
            
            internal DataColumn DeletedColumn {
                get {
                    return this.columnDeleted;
                }
            }
            
            internal DataColumn PensionarColumn {
                get {
                    return this.columnPensionar;
                }
            }
            
            internal DataColumn AreAlteVenituriColumn {
                get {
                    return this.columnAreAlteVenituri;
                }
            }
            
            internal DataColumn SolicitaDeduceriColumn {
                get {
                    return this.columnSolicitaDeduceri;
                }
            }
            
            internal DataColumn PermMuncaEliberatColumn {
                get {
                    return this.columnPermMuncaEliberat;
                }
            }
            
            internal DataColumn PermMuncaExpiraColumn {
                get {
                    return this.columnPermMuncaExpira;
                }
            }
            
            internal DataColumn PermSedereEliberatColumn {
                get {
                    return this.columnPermSedereEliberat;
                }
            }
            
            internal DataColumn PermSedereExpiraColumn {
                get {
                    return this.columnPermSedereExpira;
                }
            }
            
            internal DataColumn NrPermisMuncaColumn {
                get {
                    return this.columnNrPermisMunca;
                }
            }
            
            public AngajatiRow this[int index] {
                get {
                    return ((AngajatiRow)(this.Rows[index]));
                }
            }
            
            public event AngajatiRowChangeEventHandler AngajatiRowChanged;
            
            public event AngajatiRowChangeEventHandler AngajatiRowChanging;
            
            public event AngajatiRowChangeEventHandler AngajatiRowDeleted;
            
            public event AngajatiRowChangeEventHandler AngajatiRowDeleting;
            
            public void AddAngajatiRow(AngajatiRow row) {
                this.Rows.Add(row);
            }
            
            public AngajatiRow AddAngajatiRow(
                        int AngajatorID, 
                        string Marca, 
                        string NumeIntreg, 
                        string Nume, 
                        string Prenume, 
                        string NumeAnterior, 
                        int TitluID, 
                        System.Byte[] Poza, 
                        string PrenumeMama, 
                        string PrenumeTata, 
                        int StudiuID, 
                        short AnAbsolvire, 
                        string NrDiploma, 
                        string Descriere, 
                        bool ModIncadrare, 
                        System.Byte ProgramLucru, 
                        string Telefon, 
                        System.DateTime DataNasterii, 
                        int TaraNastereID, 
                        int JudetNastereID, 
                        string LocalitateNastere, 
                        System.Byte StareCivila, 
                        System.Byte NrCopii, 
                        string Sex, 
                        string Nationalitate, 
                        long CNP, 
                        long CNPAnterior, 
                        bool TipFisaFiscala, 
                        System.Byte AniVechimeMunca, 
                        System.Byte LuniVechimeMunca, 
                        System.Byte ZileVechimeMunca, 
                        bool AreCardBancar, 
                        int SefID, 
                        bool Activ, 
                        System.Decimal SalariuBazaActual, 
                        System.Decimal IndemnizatieConducereActual, 
                        bool PerioadaDeterminata, 
                        System.DateTime DataPanaLa, 
                        string NrContractMunca, 
                        System.DateTime DataInregContractMunca, 
                        short Invaliditate, 
                        int CategorieID, 
                        string Email, 
                        string TelMunca, 
                        bool Deleted, 
                        bool Pensionar, 
                        bool AreAlteVenituri, 
                        bool SolicitaDeduceri, 
                        System.DateTime PermMuncaEliberat, 
                        System.DateTime PermMuncaExpira, 
                        System.DateTime PermSedereEliberat, 
                        System.DateTime PermSedereExpira, 
                        int NrPermisMunca) {
                AngajatiRow rowAngajatiRow = ((AngajatiRow)(this.NewRow()));
                rowAngajatiRow.ItemArray = new object[] {
                        null,
                        AngajatorID,
                        Marca,
                        NumeIntreg,
                        Nume,
                        Prenume,
                        NumeAnterior,
                        TitluID,
                        Poza,
                        PrenumeMama,
                        PrenumeTata,
                        StudiuID,
                        AnAbsolvire,
                        NrDiploma,
                        Descriere,
                        ModIncadrare,
                        ProgramLucru,
                        Telefon,
                        DataNasterii,
                        TaraNastereID,
                        JudetNastereID,
                        LocalitateNastere,
                        StareCivila,
                        NrCopii,
                        Sex,
                        Nationalitate,
                        CNP,
                        CNPAnterior,
                        TipFisaFiscala,
                        AniVechimeMunca,
                        LuniVechimeMunca,
                        ZileVechimeMunca,
                        AreCardBancar,
                        SefID,
                        Activ,
                        SalariuBazaActual,
                        IndemnizatieConducereActual,
                        PerioadaDeterminata,
                        DataPanaLa,
                        NrContractMunca,
                        DataInregContractMunca,
                        Invaliditate,
                        CategorieID,
                        Email,
                        TelMunca,
                        Deleted,
                        Pensionar,
                        AreAlteVenituri,
                        SolicitaDeduceri,
                        PermMuncaEliberat,
                        PermMuncaExpira,
                        PermSedereEliberat,
                        PermSedereExpira,
                        NrPermisMunca};
                this.Rows.Add(rowAngajatiRow);
                return rowAngajatiRow;
            }
            
            public AngajatiRow FindByAngajatID(int AngajatID) {
                return ((AngajatiRow)(this.Rows.Find(new object[] {
                            AngajatID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                AngajatiDataTable cln = ((AngajatiDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new AngajatiDataTable();
            }
            
            internal void InitVars() {
                this.columnAngajatID = this.Columns["AngajatID"];
                this.columnAngajatorID = this.Columns["AngajatorID"];
                this.columnMarca = this.Columns["Marca"];
                this.columnNumeIntreg = this.Columns["NumeIntreg"];
                this.columnNume = this.Columns["Nume"];
                this.columnPrenume = this.Columns["Prenume"];
                this.columnNumeAnterior = this.Columns["NumeAnterior"];
                this.columnTitluID = this.Columns["TitluID"];
                this.columnPoza = this.Columns["Poza"];
                this.columnPrenumeMama = this.Columns["PrenumeMama"];
                this.columnPrenumeTata = this.Columns["PrenumeTata"];
                this.columnStudiuID = this.Columns["StudiuID"];
                this.columnAnAbsolvire = this.Columns["AnAbsolvire"];
                this.columnNrDiploma = this.Columns["NrDiploma"];
                this.columnDescriere = this.Columns["Descriere"];
                this.columnModIncadrare = this.Columns["ModIncadrare"];
                this.columnProgramLucru = this.Columns["ProgramLucru"];
                this.columnTelefon = this.Columns["Telefon"];
                this.columnDataNasterii = this.Columns["DataNasterii"];
                this.columnTaraNastereID = this.Columns["TaraNastereID"];
                this.columnJudetNastereID = this.Columns["JudetNastereID"];
                this.columnLocalitateNastere = this.Columns["LocalitateNastere"];
                this.columnStareCivila = this.Columns["StareCivila"];
                this.columnNrCopii = this.Columns["NrCopii"];
                this.columnSex = this.Columns["Sex"];
                this.columnNationalitate = this.Columns["Nationalitate"];
                this.columnCNP = this.Columns["CNP"];
                this.columnCNPAnterior = this.Columns["CNPAnterior"];
                this.columnTipFisaFiscala = this.Columns["TipFisaFiscala"];
                this.columnAniVechimeMunca = this.Columns["AniVechimeMunca"];
                this.columnLuniVechimeMunca = this.Columns["LuniVechimeMunca"];
                this.columnZileVechimeMunca = this.Columns["ZileVechimeMunca"];
                this.columnAreCardBancar = this.Columns["AreCardBancar"];
                this.columnSefID = this.Columns["SefID"];
                this.columnActiv = this.Columns["Activ"];
                this.columnSalariuBazaActual = this.Columns["SalariuBazaActual"];
                this.columnIndemnizatieConducereActual = this.Columns["IndemnizatieConducereActual"];
                this.columnPerioadaDeterminata = this.Columns["PerioadaDeterminata"];
                this.columnDataPanaLa = this.Columns["DataPanaLa"];
                this.columnNrContractMunca = this.Columns["NrContractMunca"];
                this.columnDataInregContractMunca = this.Columns["DataInregContractMunca"];
                this.columnInvaliditate = this.Columns["Invaliditate"];
                this.columnCategorieID = this.Columns["CategorieID"];
                this.columnEmail = this.Columns["Email"];
                this.columnTelMunca = this.Columns["TelMunca"];
                this.columnDeleted = this.Columns["Deleted"];
                this.columnPensionar = this.Columns["Pensionar"];
                this.columnAreAlteVenituri = this.Columns["AreAlteVenituri"];
                this.columnSolicitaDeduceri = this.Columns["SolicitaDeduceri"];
                this.columnPermMuncaEliberat = this.Columns["PermMuncaEliberat"];
                this.columnPermMuncaExpira = this.Columns["PermMuncaExpira"];
                this.columnPermSedereEliberat = this.Columns["PermSedereEliberat"];
                this.columnPermSedereExpira = this.Columns["PermSedereExpira"];
                this.columnNrPermisMunca = this.Columns["NrPermisMunca"];
            }
            
            private void InitClass() {
                this.columnAngajatID = new DataColumn("AngajatID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAngajatID);
                this.columnAngajatorID = new DataColumn("AngajatorID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAngajatorID);
                this.columnMarca = new DataColumn("Marca", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMarca);
                this.columnNumeIntreg = new DataColumn("NumeIntreg", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNumeIntreg);
                this.columnNume = new DataColumn("Nume", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNume);
                this.columnPrenume = new DataColumn("Prenume", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrenume);
                this.columnNumeAnterior = new DataColumn("NumeAnterior", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNumeAnterior);
                this.columnTitluID = new DataColumn("TitluID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTitluID);
                this.columnPoza = new DataColumn("Poza", typeof(System.Byte[]), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPoza);
                this.columnPrenumeMama = new DataColumn("PrenumeMama", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrenumeMama);
                this.columnPrenumeTata = new DataColumn("PrenumeTata", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrenumeTata);
                this.columnStudiuID = new DataColumn("StudiuID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnStudiuID);
                this.columnAnAbsolvire = new DataColumn("AnAbsolvire", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAnAbsolvire);
                this.columnNrDiploma = new DataColumn("NrDiploma", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNrDiploma);
                this.columnDescriere = new DataColumn("Descriere", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDescriere);
                this.columnModIncadrare = new DataColumn("ModIncadrare", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnModIncadrare);
                this.columnProgramLucru = new DataColumn("ProgramLucru", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProgramLucru);
                this.columnTelefon = new DataColumn("Telefon", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTelefon);
                this.columnDataNasterii = new DataColumn("DataNasterii", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDataNasterii);
                this.columnTaraNastereID = new DataColumn("TaraNastereID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTaraNastereID);
                this.columnJudetNastereID = new DataColumn("JudetNastereID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnJudetNastereID);
                this.columnLocalitateNastere = new DataColumn("LocalitateNastere", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLocalitateNastere);
                this.columnStareCivila = new DataColumn("StareCivila", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnStareCivila);
                this.columnNrCopii = new DataColumn("NrCopii", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNrCopii);
                this.columnSex = new DataColumn("Sex", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSex);
                this.columnNationalitate = new DataColumn("Nationalitate", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNationalitate);
                this.columnCNP = new DataColumn("CNP", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCNP);
                this.columnCNPAnterior = new DataColumn("CNPAnterior", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCNPAnterior);
                this.columnTipFisaFiscala = new DataColumn("TipFisaFiscala", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTipFisaFiscala);
                this.columnAniVechimeMunca = new DataColumn("AniVechimeMunca", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAniVechimeMunca);
                this.columnLuniVechimeMunca = new DataColumn("LuniVechimeMunca", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLuniVechimeMunca);
                this.columnZileVechimeMunca = new DataColumn("ZileVechimeMunca", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnZileVechimeMunca);
                this.columnAreCardBancar = new DataColumn("AreCardBancar", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAreCardBancar);
                this.columnSefID = new DataColumn("SefID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSefID);
                this.columnActiv = new DataColumn("Activ", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnActiv);
                this.columnSalariuBazaActual = new DataColumn("SalariuBazaActual", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSalariuBazaActual);
                this.columnIndemnizatieConducereActual = new DataColumn("IndemnizatieConducereActual", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIndemnizatieConducereActual);
                this.columnPerioadaDeterminata = new DataColumn("PerioadaDeterminata", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPerioadaDeterminata);
                this.columnDataPanaLa = new DataColumn("DataPanaLa", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDataPanaLa);
                this.columnNrContractMunca = new DataColumn("NrContractMunca", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNrContractMunca);
                this.columnDataInregContractMunca = new DataColumn("DataInregContractMunca", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDataInregContractMunca);
                this.columnInvaliditate = new DataColumn("Invaliditate", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnInvaliditate);
                this.columnCategorieID = new DataColumn("CategorieID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCategorieID);
                this.columnEmail = new DataColumn("Email", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEmail);
                this.columnTelMunca = new DataColumn("TelMunca", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTelMunca);
                this.columnDeleted = new DataColumn("Deleted", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDeleted);
                this.columnPensionar = new DataColumn("Pensionar", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPensionar);
                this.columnAreAlteVenituri = new DataColumn("AreAlteVenituri", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAreAlteVenituri);
                this.columnSolicitaDeduceri = new DataColumn("SolicitaDeduceri", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSolicitaDeduceri);
                this.columnPermMuncaEliberat = new DataColumn("PermMuncaEliberat", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPermMuncaEliberat);
                this.columnPermMuncaExpira = new DataColumn("PermMuncaExpira", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPermMuncaExpira);
                this.columnPermSedereEliberat = new DataColumn("PermSedereEliberat", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPermSedereEliberat);
                this.columnPermSedereExpira = new DataColumn("PermSedereExpira", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPermSedereExpira);
                this.columnNrPermisMunca = new DataColumn("NrPermisMunca", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNrPermisMunca);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnAngajatID}, true));
                this.columnAngajatID.AutoIncrement = true;
                this.columnAngajatID.AllowDBNull = false;
                this.columnAngajatID.ReadOnly = true;
                this.columnAngajatID.Unique = true;
                this.columnAngajatorID.AllowDBNull = false;
                this.columnMarca.AllowDBNull = false;
                this.columnNume.AllowDBNull = false;
                this.columnPrenume.AllowDBNull = false;
                this.columnNumeAnterior.AllowDBNull = false;
                this.columnPrenumeMama.AllowDBNull = false;
                this.columnPrenumeTata.AllowDBNull = false;
                this.columnStudiuID.AllowDBNull = false;
                this.columnAnAbsolvire.AllowDBNull = false;
                this.columnNrDiploma.AllowDBNull = false;
                this.columnModIncadrare.AllowDBNull = false;
                this.columnProgramLucru.AllowDBNull = false;
                this.columnDataNasterii.AllowDBNull = false;
                this.columnTaraNastereID.AllowDBNull = false;
                this.columnJudetNastereID.AllowDBNull = false;
                this.columnLocalitateNastere.AllowDBNull = false;
                this.columnStareCivila.AllowDBNull = false;
                this.columnNrCopii.AllowDBNull = false;
                this.columnSex.AllowDBNull = false;
                this.columnNationalitate.AllowDBNull = false;
                this.columnCNP.AllowDBNull = false;
                this.columnCNPAnterior.AllowDBNull = false;
                this.columnTipFisaFiscala.AllowDBNull = false;
                this.columnAniVechimeMunca.AllowDBNull = false;
                this.columnZileVechimeMunca.AllowDBNull = false;
                this.columnAreCardBancar.AllowDBNull = false;
                this.columnNrContractMunca.AllowDBNull = false;
                this.columnDataInregContractMunca.AllowDBNull = false;
                this.columnCategorieID.AllowDBNull = false;
                this.columnEmail.AllowDBNull = false;
                this.columnTelMunca.AllowDBNull = false;
                this.columnDeleted.AllowDBNull = false;
                this.columnPensionar.AllowDBNull = false;
                this.columnNrPermisMunca.AllowDBNull = false;
            }
            
            public AngajatiRow NewAngajatiRow() {
                return ((AngajatiRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new AngajatiRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(AngajatiRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.AngajatiRowChanged != null)) {
                    this.AngajatiRowChanged(this, new AngajatiRowChangeEvent(((AngajatiRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.AngajatiRowChanging != null)) {
                    this.AngajatiRowChanging(this, new AngajatiRowChangeEvent(((AngajatiRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.AngajatiRowDeleted != null)) {
                    this.AngajatiRowDeleted(this, new AngajatiRowChangeEvent(((AngajatiRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.AngajatiRowDeleting != null)) {
                    this.AngajatiRowDeleting(this, new AngajatiRowChangeEvent(((AngajatiRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveAngajatiRow(AngajatiRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class AngajatiRow : DataRow {
            
            private AngajatiDataTable tableAngajati;
            
            internal AngajatiRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableAngajati = ((AngajatiDataTable)(this.Table));
            }
            
            public int AngajatID {
                get {
                    return ((int)(this[this.tableAngajati.AngajatIDColumn]));
                }
                set {
                    this[this.tableAngajati.AngajatIDColumn] = value;
                }
            }
            
            public int AngajatorID {
                get {
                    return ((int)(this[this.tableAngajati.AngajatorIDColumn]));
                }
                set {
                    this[this.tableAngajati.AngajatorIDColumn] = value;
                }
            }
            
            public string Marca {
                get {
                    return ((string)(this[this.tableAngajati.MarcaColumn]));
                }
                set {
                    this[this.tableAngajati.MarcaColumn] = value;
                }
            }
            
            public string NumeIntreg {
                get {
                    try {
                        return ((string)(this[this.tableAngajati.NumeIntregColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.NumeIntregColumn] = value;
                }
            }
            
            public string Nume {
                get {
                    return ((string)(this[this.tableAngajati.NumeColumn]));
                }
                set {
                    this[this.tableAngajati.NumeColumn] = value;
                }
            }
            
            public string Prenume {
                get {
                    return ((string)(this[this.tableAngajati.PrenumeColumn]));
                }
                set {
                    this[this.tableAngajati.PrenumeColumn] = value;
                }
            }
            
            public string NumeAnterior {
                get {
                    return ((string)(this[this.tableAngajati.NumeAnteriorColumn]));
                }
                set {
                    this[this.tableAngajati.NumeAnteriorColumn] = value;
                }
            }
            
            public int TitluID {
                get {
                    try {
                        return ((int)(this[this.tableAngajati.TitluIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.TitluIDColumn] = value;
                }
            }
            
            public System.Byte[] Poza {
                get {
                    try {
                        return ((System.Byte[])(this[this.tableAngajati.PozaColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.PozaColumn] = value;
                }
            }
            
            public string PrenumeMama {
                get {
                    return ((string)(this[this.tableAngajati.PrenumeMamaColumn]));
                }
                set {
                    this[this.tableAngajati.PrenumeMamaColumn] = value;
                }
            }
            
            public string PrenumeTata {
                get {
                    return ((string)(this[this.tableAngajati.PrenumeTataColumn]));
                }
                set {
                    this[this.tableAngajati.PrenumeTataColumn] = value;
                }
            }
            
            public int StudiuID {
                get {
                    return ((int)(this[this.tableAngajati.StudiuIDColumn]));
                }
                set {
                    this[this.tableAngajati.StudiuIDColumn] = value;
                }
            }
            
            public short AnAbsolvire {
                get {
                    return ((short)(this[this.tableAngajati.AnAbsolvireColumn]));
                }
                set {
                    this[this.tableAngajati.AnAbsolvireColumn] = value;
                }
            }
            
            public string NrDiploma {
                get {
                    return ((string)(this[this.tableAngajati.NrDiplomaColumn]));
                }
                set {
                    this[this.tableAngajati.NrDiplomaColumn] = value;
                }
            }
            
            public string Descriere {
                get {
                    try {
                        return ((string)(this[this.tableAngajati.DescriereColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.DescriereColumn] = value;
                }
            }
            
            public bool ModIncadrare {
                get {
                    return ((bool)(this[this.tableAngajati.ModIncadrareColumn]));
                }
                set {
                    this[this.tableAngajati.ModIncadrareColumn] = value;
                }
            }
            
            public System.Byte ProgramLucru {
                get {
                    return ((System.Byte)(this[this.tableAngajati.ProgramLucruColumn]));
                }
                set {
                    this[this.tableAngajati.ProgramLucruColumn] = value;
                }
            }
            
            public string Telefon {
                get {
                    try {
                        return ((string)(this[this.tableAngajati.TelefonColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.TelefonColumn] = value;
                }
            }
            
            public System.DateTime DataNasterii {
                get {
                    return ((System.DateTime)(this[this.tableAngajati.DataNasteriiColumn]));
                }
                set {
                    this[this.tableAngajati.DataNasteriiColumn] = value;
                }
            }
            
            public int TaraNastereID {
                get {
                    return ((int)(this[this.tableAngajati.TaraNastereIDColumn]));
                }
                set {
                    this[this.tableAngajati.TaraNastereIDColumn] = value;
                }
            }
            
            public int JudetNastereID {
                get {
                    return ((int)(this[this.tableAngajati.JudetNastereIDColumn]));
                }
                set {
                    this[this.tableAngajati.JudetNastereIDColumn] = value;
                }
            }
            
            public string LocalitateNastere {
                get {
                    return ((string)(this[this.tableAngajati.LocalitateNastereColumn]));
                }
                set {
                    this[this.tableAngajati.LocalitateNastereColumn] = value;
                }
            }
            
            public System.Byte StareCivila {
                get {
                    return ((System.Byte)(this[this.tableAngajati.StareCivilaColumn]));
                }
                set {
                    this[this.tableAngajati.StareCivilaColumn] = value;
                }
            }
            
            public System.Byte NrCopii {
                get {
                    return ((System.Byte)(this[this.tableAngajati.NrCopiiColumn]));
                }
                set {
                    this[this.tableAngajati.NrCopiiColumn] = value;
                }
            }
            
            public string Sex {
                get {
                    return ((string)(this[this.tableAngajati.SexColumn]));
                }
                set {
                    this[this.tableAngajati.SexColumn] = value;
                }
            }
            
            public string Nationalitate {
                get {
                    return ((string)(this[this.tableAngajati.NationalitateColumn]));
                }
                set {
                    this[this.tableAngajati.NationalitateColumn] = value;
                }
            }
            
            public long CNP {
                get {
                    return ((long)(this[this.tableAngajati.CNPColumn]));
                }
                set {
                    this[this.tableAngajati.CNPColumn] = value;
                }
            }
            
            public long CNPAnterior {
                get {
                    return ((long)(this[this.tableAngajati.CNPAnteriorColumn]));
                }
                set {
                    this[this.tableAngajati.CNPAnteriorColumn] = value;
                }
            }
            
            public bool TipFisaFiscala {
                get {
                    return ((bool)(this[this.tableAngajati.TipFisaFiscalaColumn]));
                }
                set {
                    this[this.tableAngajati.TipFisaFiscalaColumn] = value;
                }
            }
            
            public System.Byte AniVechimeMunca {
                get {
                    return ((System.Byte)(this[this.tableAngajati.AniVechimeMuncaColumn]));
                }
                set {
                    this[this.tableAngajati.AniVechimeMuncaColumn] = value;
                }
            }
            
            public System.Byte LuniVechimeMunca {
                get {
                    try {
                        return ((System.Byte)(this[this.tableAngajati.LuniVechimeMuncaColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.LuniVechimeMuncaColumn] = value;
                }
            }
            
            public System.Byte ZileVechimeMunca {
                get {
                    return ((System.Byte)(this[this.tableAngajati.ZileVechimeMuncaColumn]));
                }
                set {
                    this[this.tableAngajati.ZileVechimeMuncaColumn] = value;
                }
            }
            
            public bool AreCardBancar {
                get {
                    return ((bool)(this[this.tableAngajati.AreCardBancarColumn]));
                }
                set {
                    this[this.tableAngajati.AreCardBancarColumn] = value;
                }
            }
            
            public int SefID {
                get {
                    try {
                        return ((int)(this[this.tableAngajati.SefIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.SefIDColumn] = value;
                }
            }
            
            public bool Activ {
                get {
                    try {
                        return ((bool)(this[this.tableAngajati.ActivColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.ActivColumn] = value;
                }
            }
            
            public System.Decimal SalariuBazaActual {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableAngajati.SalariuBazaActualColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.SalariuBazaActualColumn] = value;
                }
            }
            
            public System.Decimal IndemnizatieConducereActual {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableAngajati.IndemnizatieConducereActualColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.IndemnizatieConducereActualColumn] = value;
                }
            }
            
            public bool PerioadaDeterminata {
                get {
                    try {
                        return ((bool)(this[this.tableAngajati.PerioadaDeterminataColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.PerioadaDeterminataColumn] = value;
                }
            }
            
            public System.DateTime DataPanaLa {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableAngajati.DataPanaLaColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.DataPanaLaColumn] = value;
                }
            }
            
            public string NrContractMunca {
                get {
                    return ((string)(this[this.tableAngajati.NrContractMuncaColumn]));
                }
                set {
                    this[this.tableAngajati.NrContractMuncaColumn] = value;
                }
            }
            
            public System.DateTime DataInregContractMunca {
                get {
                    return ((System.DateTime)(this[this.tableAngajati.DataInregContractMuncaColumn]));
                }
                set {
                    this[this.tableAngajati.DataInregContractMuncaColumn] = value;
                }
            }
            
            public short Invaliditate {
                get {
                    try {
                        return ((short)(this[this.tableAngajati.InvaliditateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.InvaliditateColumn] = value;
                }
            }
            
            public int CategorieID {
                get {
                    return ((int)(this[this.tableAngajati.CategorieIDColumn]));
                }
                set {
                    this[this.tableAngajati.CategorieIDColumn] = value;
                }
            }
            
            public string Email {
                get {
                    return ((string)(this[this.tableAngajati.EmailColumn]));
                }
                set {
                    this[this.tableAngajati.EmailColumn] = value;
                }
            }
            
            public string TelMunca {
                get {
                    return ((string)(this[this.tableAngajati.TelMuncaColumn]));
                }
                set {
                    this[this.tableAngajati.TelMuncaColumn] = value;
                }
            }
            
            public bool Deleted {
                get {
                    return ((bool)(this[this.tableAngajati.DeletedColumn]));
                }
                set {
                    this[this.tableAngajati.DeletedColumn] = value;
                }
            }
            
            public bool Pensionar {
                get {
                    return ((bool)(this[this.tableAngajati.PensionarColumn]));
                }
                set {
                    this[this.tableAngajati.PensionarColumn] = value;
                }
            }
            
            public bool AreAlteVenituri {
                get {
                    try {
                        return ((bool)(this[this.tableAngajati.AreAlteVenituriColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.AreAlteVenituriColumn] = value;
                }
            }
            
            public bool SolicitaDeduceri {
                get {
                    try {
                        return ((bool)(this[this.tableAngajati.SolicitaDeduceriColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.SolicitaDeduceriColumn] = value;
                }
            }
            
            public System.DateTime PermMuncaEliberat {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableAngajati.PermMuncaEliberatColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.PermMuncaEliberatColumn] = value;
                }
            }
            
            public System.DateTime PermMuncaExpira {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableAngajati.PermMuncaExpiraColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.PermMuncaExpiraColumn] = value;
                }
            }
            
            public System.DateTime PermSedereEliberat {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableAngajati.PermSedereEliberatColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.PermSedereEliberatColumn] = value;
                }
            }
            
            public System.DateTime PermSedereExpira {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableAngajati.PermSedereExpiraColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAngajati.PermSedereExpiraColumn] = value;
                }
            }
            
            public int NrPermisMunca {
                get {
                    return ((int)(this[this.tableAngajati.NrPermisMuncaColumn]));
                }
                set {
                    this[this.tableAngajati.NrPermisMuncaColumn] = value;
                }
            }
            
            public bool IsNumeIntregNull() {
                return this.IsNull(this.tableAngajati.NumeIntregColumn);
            }
            
            public void SetNumeIntregNull() {
                this[this.tableAngajati.NumeIntregColumn] = System.Convert.DBNull;
            }
            
            public bool IsTitluIDNull() {
                return this.IsNull(this.tableAngajati.TitluIDColumn);
            }
            
            public void SetTitluIDNull() {
                this[this.tableAngajati.TitluIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsPozaNull() {
                return this.IsNull(this.tableAngajati.PozaColumn);
            }
            
            public void SetPozaNull() {
                this[this.tableAngajati.PozaColumn] = System.Convert.DBNull;
            }
            
            public bool IsDescriereNull() {
                return this.IsNull(this.tableAngajati.DescriereColumn);
            }
            
            public void SetDescriereNull() {
                this[this.tableAngajati.DescriereColumn] = System.Convert.DBNull;
            }
            
            public bool IsTelefonNull() {
                return this.IsNull(this.tableAngajati.TelefonColumn);
            }
            
            public void SetTelefonNull() {
                this[this.tableAngajati.TelefonColumn] = System.Convert.DBNull;
            }
            
            public bool IsLuniVechimeMuncaNull() {
                return this.IsNull(this.tableAngajati.LuniVechimeMuncaColumn);
            }
            
            public void SetLuniVechimeMuncaNull() {
                this[this.tableAngajati.LuniVechimeMuncaColumn] = System.Convert.DBNull;
            }
            
            public bool IsSefIDNull() {
                return this.IsNull(this.tableAngajati.SefIDColumn);
            }
            
            public void SetSefIDNull() {
                this[this.tableAngajati.SefIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsActivNull() {
                return this.IsNull(this.tableAngajati.ActivColumn);
            }
            
            public void SetActivNull() {
                this[this.tableAngajati.ActivColumn] = System.Convert.DBNull;
            }
            
            public bool IsSalariuBazaActualNull() {
                return this.IsNull(this.tableAngajati.SalariuBazaActualColumn);
            }
            
            public void SetSalariuBazaActualNull() {
                this[this.tableAngajati.SalariuBazaActualColumn] = System.Convert.DBNull;
            }
            
            public bool IsIndemnizatieConducereActualNull() {
                return this.IsNull(this.tableAngajati.IndemnizatieConducereActualColumn);
            }
            
            public void SetIndemnizatieConducereActualNull() {
                this[this.tableAngajati.IndemnizatieConducereActualColumn] = System.Convert.DBNull;
            }
            
            public bool IsPerioadaDeterminataNull() {
                return this.IsNull(this.tableAngajati.PerioadaDeterminataColumn);
            }
            
            public void SetPerioadaDeterminataNull() {
                this[this.tableAngajati.PerioadaDeterminataColumn] = System.Convert.DBNull;
            }
            
            public bool IsDataPanaLaNull() {
                return this.IsNull(this.tableAngajati.DataPanaLaColumn);
            }
            
            public void SetDataPanaLaNull() {
                this[this.tableAngajati.DataPanaLaColumn] = System.Convert.DBNull;
            }
            
            public bool IsInvaliditateNull() {
                return this.IsNull(this.tableAngajati.InvaliditateColumn);
            }
            
            public void SetInvaliditateNull() {
                this[this.tableAngajati.InvaliditateColumn] = System.Convert.DBNull;
            }
            
            public bool IsAreAlteVenituriNull() {
                return this.IsNull(this.tableAngajati.AreAlteVenituriColumn);
            }
            
            public void SetAreAlteVenituriNull() {
                this[this.tableAngajati.AreAlteVenituriColumn] = System.Convert.DBNull;
            }
            
            public bool IsSolicitaDeduceriNull() {
                return this.IsNull(this.tableAngajati.SolicitaDeduceriColumn);
            }
            
            public void SetSolicitaDeduceriNull() {
                this[this.tableAngajati.SolicitaDeduceriColumn] = System.Convert.DBNull;
            }
            
            public bool IsPermMuncaEliberatNull() {
                return this.IsNull(this.tableAngajati.PermMuncaEliberatColumn);
            }
            
            public void SetPermMuncaEliberatNull() {
                this[this.tableAngajati.PermMuncaEliberatColumn] = System.Convert.DBNull;
            }
            
            public bool IsPermMuncaExpiraNull() {
                return this.IsNull(this.tableAngajati.PermMuncaExpiraColumn);
            }
            
            public void SetPermMuncaExpiraNull() {
                this[this.tableAngajati.PermMuncaExpiraColumn] = System.Convert.DBNull;
            }
            
            public bool IsPermSedereEliberatNull() {
                return this.IsNull(this.tableAngajati.PermSedereEliberatColumn);
            }
            
            public void SetPermSedereEliberatNull() {
                this[this.tableAngajati.PermSedereEliberatColumn] = System.Convert.DBNull;
            }
            
            public bool IsPermSedereExpiraNull() {
                return this.IsNull(this.tableAngajati.PermSedereExpiraColumn);
            }
            
            public void SetPermSedereExpiraNull() {
                this[this.tableAngajati.PermSedereExpiraColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class AngajatiRowChangeEvent : EventArgs {
            
            private AngajatiRow eventRow;
            
            private DataRowAction eventAction;
            
            public AngajatiRowChangeEvent(AngajatiRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public AngajatiRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
