/*

   Wednesday, August 17, 2005 7:01:38 PM

   User: 

   Server: localhost

   Database: SiemensHR_Test

   Application: 

*/



BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.Angajati ADD
	Lichidat bit NOT NULL CONSTRAINT DF_Angajati_Lichidat DEFAULT (0)
GO
COMMIT
